title: Rohit Kumar
author: Rohit Kumar
email: davasrohit[AT]gmail[DOT]com
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Gain a deeper understanding of my skills, accomplishments, and thoughts through my personal portfolio and blog website.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

linkedin_username: rohitdavas
github_username:  rohitdavas
instagram_username: rohit_davas
markdown: kramdown
resume: assets/resumes/RohitKumar-chronological-order-resume.pdf
# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
header_pages:
  - index.md
  - blogs.md
  - Competitions.md
  - Never Too Late.md
  - Projects.md    
  - Education and Interests.md                                              
  - assets/resumes/RohitKumar-chronological-order-resume.pdf
  
# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true

# Path: _includes/head.html
