title: Rohit Kumar
theme: minima
minima:
  skin: dark 
markdown: kramdown
social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/rohitdavas/" }
    - { platform: github, user_url: "https://github.com/rohitdavas" }
