title: Rohit Kumar
author: Rohit Kumar
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This is my personal, simple webpage which serves as my portfolio and blog page.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

linkedin_username: rohitdavas
github_username:  rohitdavas

minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/rohitdavas/" }
    - { platform: github, user_url: "https://github.com/rohitdavas" }
markdown: kramdown


# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
header_pages:
  - index.md
  - blogs.md
  - Competitions.md                 
  - Education and Interests.md                         
  - Contact.md                      
  - Projects.md
# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true

# Path: _includes/head.html

